# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [48]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [49]:
# Importing the dataset
pokemon = pd.read_csv('pokemon.csv')

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [14]:
# your code here
pokemon['Computed Total'] = pokemon[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']].sum(axis=1)

In [4]:
pokemon['Matches'] = pokemon['Total'] == pokemon['Computed Total']

# Verify if all values in 'Matches' are True
all_match = pokemon['Matches'].all()

print("Does the 'Total' match the sum of the individual fields for all Pokémon? ", all_match)
print(pokemon)

Does the 'Total' match the sum of the individual fields for all Pokémon?  True
       #                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49
1      2                Ivysaur    Grass  Poison    405  60      62       63
2      3               Venusaur    Grass  Poison    525  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123
4      4             Charmander     Fire     NaN    309  39      52       43
..   ...                    ...      ...     ...    ...  ..     ...      ...
795  719                Diancie     Rock   Fairy    600  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
799  721              Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Computed Total  Matches
0         65       65     45           1      False             318     True
1         80       80     60           1      False             405     True
2        100      100     80           1      False             525     True
3        122      120     80           1      False             625     True
4         60       50     65           1      False             309     True
..       ...      ...    ...         ...        ...             ...      ...
795      100      150     50           6       True             600     True
796      160      110    110           6       True             700     True
797      150      130     70           6       True             600     True
798      170      130     80           6       True             680     True
799      130       90     70           6       True             600     True

[800 rows x 15 columns]

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [36]:
pokemon['Type 2'].fillna('None', inplace=True)  # Replace NaNs with 'None'
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Stacking 'Type 1' and 'Type 2' into a 2D array for the encoder
types_combined = pokemon[['Type 1', 'Type 2']]

#merge_value = pd.concat([pokemon['Type 1'], pokemon['Type 2']]).unique()

# Fit and transform the data
types_encoded = encoder.fit_transform(types_combined)



# This returns an array, so if you want it back in a DataFrame:
types_encoded_df = pd.DataFrame(types_encoded, columns=encoder.get_feature_names_out(['Type 1', 'Type 2']))
types_encoded_df

,Type 1_Bug,Type 1_Dark,Type 1_Dragon,Type 1_Electric,Type 1_Fairy,Type 1_Fighting,Type 1_Fire,Type 1_Flying,Type 1_Ghost,Type 1_Grass,...,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_None,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
799,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [56]:
pokemon['Type 2'].fillna('None', inplace=True)

# Combine 'Type 1' and 'Type 2' into a single Series of set
combined_types = pokemon.apply(lambda row: {row['Type 1'], row['Type 2']}, axis=1)

# Transform this Series of sets/lists into a format suitable for OneHotEncoder: a list of lists
combined_types_list = combined_types.apply(list).tolist()

# Initialize and apply OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
types_encoded = encoder.fit_transform(combined_types_list)

# Create a DataFrame from the encoded array, using type names as column headers
types_encoded_df = pd.DataFrame(types_encoded, columns=encoder.get_feature_names_out())

print(types_encoded_df)

     x0_Bug  x0_Dark  x0_Dragon  x0_Electric  x0_Fairy  x0_Fighting  x0_Fire  \
0       0.0      0.0        0.0          0.0       0.0          0.0      0.0
1       0.0      0.0        0.0          0.0       0.0          0.0      0.0
2       0.0      0.0        0.0          0.0       0.0          0.0      0.0
3       0.0      0.0        0.0          0.0       0.0          0.0      0.0
4       0.0      0.0        0.0          0.0       0.0          0.0      1.0
..      ...      ...        ...          ...       ...          ...      ...
795     0.0      0.0        0.0          0.0       0.0          0.0      0.0
796     0.0      0.0        0.0          0.0       0.0          0.0      0.0
797     0.0      0.0        0.0          0.0       0.0          0.0      0.0
798     0.0      1.0        0.0          0.0       0.0          0.0      0.0
799     0.0      0.0        0.0          0.0       0.0          0.0      1.0

     x0_Flying  x0_Ghost  x0_Grass  ...  x1_Grass  x1_Ground  x1_Ice  x1_None  \
0          0.0       0.0       1.0  ...       0.0        0.0     0.0      0.0
1          0.0       0.0       1.0  ...       0.0        0.0     0.0      0.0
2          0.0       0.0       1.0  ...       0.0        0.0     0.0      0.0
3          0.0       0.0       1.0  ...       0.0        0.0     0.0      0.0
4          0.0       0.0       0.0  ...       0.0        0.0     0.0      1.0
..         ...       ...       ...  ...       ...        ...     ...      ...
795        0.0       0.0       0.0  ...       0.0        0.0     0.0      0.0
796        0.0       0.0       0.0  ...       0.0        0.0     0.0      0.0
797        0.0       1.0       0.0  ...       0.0        0.0     0.0      0.0
798        0.0       0.0       0.0  ...       0.0        0.0     0.0      0.0
799        0.0       0.0       0.0  ...       0.0        0.0     0.0      0.0

     x1_Normal  x1_Poison  x1_Psychic  x1_Rock  x1_Steel  x1_Water
0          0.0        1.0         0.0      0.0       0.0       0.0
1          0.0        1.0         0.0      0.0       0.0       0.0
2          0.0        1.0         0.0      0.0       0.0       0.0
3          0.0        1.0         0.0      0.0       0.0       0.0
4          0.0        0.0         0.0      0.0       0.0       0.0
..         ...        ...         ...      ...       ...       ...
795        0.0        0.0         0.0      0.0       0.0       0.0
796        0.0        0.0         0.0      0.0       0.0       0.0
797        0.0        0.0         1.0      0.0       0.0       0.0
798        0.0        0.0         1.0      0.0       0.0       0.0
799        0.0        0.0         0.0      0.0       0.0       1.0

[800 rows x 36 columns]

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [62]:
pokemon['Type 2'].fillna('None', inplace=True)

# Ensure 'Total' is numeric
pokemon['Total'] = pd.to_numeric(pokemon['Total'], errors='raise')

# calculate correlations as intended
numeric_df = pokemon.select_dtypes(include=['number'])
correlation_matrix = numeric_df.corr()

# Analyze the correlation of 'Total' with encoded type fields
total_correlations = correlation_matrix['Total'].sort_values(ascending=False)
print(total_correlations)

Total         1.000000
Sp. Atk       0.747250
Attack        0.736211
Sp. Def       0.717609
HP            0.618748
Defense       0.612787
Speed         0.575943
#             0.119813
Generation    0.048384
Name: Total, dtype: float64

In [65]:
# Identify the type with highest correlation to 'Total'
highest_correlation_type = total_correlations[1:].idxmax()
highest_correlation_value = total_correlations[1:].max()

print(f"The Pokémon type most strongly correlated with a high 'Total' is {highest_correlation_type} with a correlation of {highest_correlation_value}.")

The Pokémon type most strongly correlated with a high 'Total' is Sp. Atk with a correlation of 0.747249860844327.

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here